[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "20" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[template.environment]
  NEXT_PUBLIC_SITE_URL = "Set to your Netlify URL, e.g. https://parsaw.netlify.app"
  GITHUB_CLIENT_ID = "GitHub OAuth App Client ID"
  GITHUB_CLIENT_SECRET = "GitHub OAuth App Client Secret"
  NEXT_PUBLIC_GITHUB_CLIENT_ID = "Duplicate of Client ID for client-side CMS init"

[[headers]]
  for = "/admin"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://cdn.jsdelivr.net https://github.com https://api.github.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:; frame-src 'self' https://github.com https://*.github.com;"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://cdn.jsdelivr.net https://github.com https://api.github.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:; frame-src 'self' https://github.com https://*.github.com;"
