backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
  branch: main
  base_url: http://localhost:3000
  auth_endpoint: /api/decap/oauth/authorize
  site_domain: http://localhost:3000

local_backend: false

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: pages
    label: Pages
    files:
      - file: content/pages/home.json
        label: Home
        name: home
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Tagline, name: tagline, widget: string }
          - { label: Value Proposition, name: value, widget: text }
          - { label: CTA Label, name: cta, widget: string }
      - file: content/pages/about.json
        label: About
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Hero, name: hero, widget: text }
          - { label: Journey, name: journey, widget: text }
          - { label: Skills, name: skills, widget: list, allow_add: false, fields: [ {label: Section, name: section, widget: string}, {label: Items, name: items, widget: text} ] }
      - file: content/pages/contact.json
        label: Contact
        name: contact
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Headline, name: headline, widget: string }
          - { label: Intro, name: intro, widget: text }
          - { label: Email, name: email, widget: string }
          - { label: LinkedIn, name: linkedin, widget: string }
          - { label: CTA, name: cta, widget: string }
  - name: projects
    label: Projects
    label_singular: Project
    folder: content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Summary, name: summary, widget: text }
      - { label: Category, name: category, widget: select, options: ["GENERATIVE AI", "WEB3", "IMMERSIVE EXPERIENCES", "FILM", "OTHER"] }
      - { label: Image, name: image, widget: image }
      - { label: Featured, name: featured, widget: boolean, default: false }
